name: Publish to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.6.3
      - name: Cache Maven artifacts
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Cache node
        uses: actions/cache@v2
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-
#       - name: Build and publish package ${{ matrix.java-version }}
#         run: |
#           mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false
#           mvn -B -DskipTests -Pskip-shaded-web-jar -Pskip-tools-jar source:jar deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-only:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 18, 19-ea ]
    steps:
      - uses: actions/checkout@v2
      - run: |
          download_url="https://api.adoptium.net/v3/binary/latest/19/ea/linux/x64/jdk/hotspot/normal/eclipse"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '19.0.0'
          architecture: x64
#       - uses: actions/setup-java@v2
#         with:
#           java-version: ${{ matrix.java-version }}
#           distribution: temurin
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.6.3
#       - name: Cache Maven artifacts
#         uses: actions/cache@v2
#         with:
#           path: ~/.m2/repository
#           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#           restore-keys: |
#             ${{ runner.os }}-maven-
      - name: Cache node
        uses: actions/cache@v2
        with:
          path: web-bundle/node
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os}}-node-
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: web-bundle/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/pom.xml', '**/package.json') }}
          restore-keys: |
            ${{ runner.os}}-node_modules-
      
      - name: Build ${{ matrix.java-version }}
        run: |
          java -version
          mvn --version
          mvn -B versions:set -DnewVersion=$GITHUB_SHA -DgenerateBackupPoms=false
          mvn -B clean test -X
